export const LANDING_NAV = [
  { label: 'Home', href: '#home' },
  { label: 'Internships', href: '/portal/student' },
  { label: 'Startup Journey', href: '#startup' },
  { label: 'Resources', href: '#resources', hasDropdown: true },
];

export const PARTNERS = [
  { name: 'Founders Hub', logo: 'FH' },
  { name: 'ITG', logo: 'ITG' },
  { name: 'National Expansion Plan', logo: 'NEP' },
  { name: 'TechBridge', logo: 'TB' },
  { name: 'SkillForge', logo: 'SF' },
  { name: 'NextGen Labs', logo: 'NL' },
];

export const INTERNSHIP_POSTINGS = [
  {
    id: 1,
    title: 'Frontend Development',
    company: 'InternHub Partner',
    duration: '8 Weeks',
    type: 'Virtual',
    spots: 45,
    level: 'Beginner',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=240&fit=crop',
    tags: ['React', 'JavaScript', 'CSS'],
    trending: true,
  },
  {
    id: 2,
    title: 'Backend Development',
    company: 'InternHub Partner',
    duration: '10 Weeks',
    type: 'Virtual',
    spots: 32,
    level: 'Intermediate',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=240&fit=crop',
    tags: ['Node.js', 'MongoDB', 'API'],
    trending: true,
  },
  {
    id: 3,
    title: 'UI/UX Design',
    company: 'InternHub Partner',
    duration: '6 Weeks',
    type: 'Virtual',
    spots: 28,
    level: 'Beginner',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=240&fit=crop',
    tags: ['Figma', 'Prototyping', 'Research'],
    trending: false,
  },
  {
    id: 4,
    title: 'Data Science',
    company: 'InternHub Partner',
    duration: '12 Weeks',
    type: 'Virtual',
    spots: 20,
    level: 'Intermediate',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=240&fit=crop',
    tags: ['Python', 'ML', 'Analytics'],
    trending: true,
  },
  {
    id: 5,
    title: 'Mobile App Development',
    company: 'InternHub Partner',
    duration: '10 Weeks',
    type: 'Virtual',
    spots: 25,
    level: 'Intermediate',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=240&fit=crop',
    tags: ['Flutter', 'Dart', 'Firebase'],
    trending: false,
  },
  {
    id: 6,
    title: 'Digital Marketing',
    company: 'InternHub Partner',
    duration: '6 Weeks',
    type: 'Virtual',
    spots: 40,
    level: 'Beginner',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=240&fit=crop',
    tags: ['SEO', 'Social Media', 'Analytics'],
    trending: false,
  },
  {
    id: 7,
    title: 'Cybersecurity',
    company: 'InternHub Partner',
    duration: '8 Weeks',
    type: 'Virtual',
    spots: 18,
    level: 'Advanced',
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=240&fit=crop',
    tags: ['Network', 'Ethical Hacking', 'Security'],
    trending: false,
  },
  {
    id: 8,
    title: 'Cloud Computing',
    company: 'InternHub Partner',
    duration: '10 Weeks',
    type: 'Virtual',
    spots: 22,
    level: 'Intermediate',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=240&fit=crop',
    tags: ['AWS', 'Docker', 'DevOps'],
    trending: true,
  },
];

export const LANDING_STATS = [
  { value: '200K+', label: 'Active Students' },
  { value: '10+', label: 'Tech Tracks' },
  { value: '92.5%', label: 'Placement Rate' },
  { value: '500+', label: 'Partner Companies' },
];
